### ISSUE TITLE
Use sendAnimation method

### ISSUE THREAD

**Issue by GabrielRF** [GabrielRF/Video2Telegram#1]
Using this method will make the gif compatible with more devices

SendAnimation is not yet available on PyTelegramBotAPI

https://github.com/eternnoir/pyTelegramBotAPI/issues/542

**Comment by intoroddex** [comment]
I want it +1

**Comment by GabrielRF** [comment]
@intoroddex It's working now

**Comment by intoroddex** [comment]
@GabrielRF I tried it and it not worked for me

**Comment by GabrielRF** [comment]
@intoroddex Can you show me more details of how you tested? Maybe some code on a gist..

**Comment by intoroddex** [comment]
@GabrielRF

bot.send_animation(rata, gifs)

AttributeError: 'TeleBot' object has no attribute 'send_animation'

"

**Comment by intoroddex** [comment]
Yeah , solved send_document :') 

@GabrielRF
